### ISSUE TITLE
how does this work?

### ISSUE THREAD

**Issue by jtkeyva** [dtkdt100/notification_when_app_is_killed#1]
what does this do exactly and how do i get a notification?

**Comment by dtkdt100** [comment]
Hi, @jtkeyva 
This is still a concept package, it is not fully working yet :(

I will write in the README, sorry.

I will let you know when it is working, currently only android has been tested and working.

If you want to use it anyway please look at the example

**Comment by jtkeyva** [comment]
ok thanks. i'm on ios and curious as to how it worked and what it did. intruiging title. like how do you get a notification if the app is not open or responding?

i look forward to the progress :)

**Comment by dtkdt100** [comment]
Hi, this package is fully working now. Plesase checkout [version 0.0.2](https://pub.dev/packages/notification_when_app_is_killed).

This package developed with this acrticle https://medium.com/@gdelataillade/displaying-a-notification-when-your-flutter-app-is-killed-4ef25cc3f193 and with [gdelataillade](https://github.com/gdelataillade)'s help

**Comment by jtkeyva** [comment]
thank you it's working now.
EDIT:
Sometimes it's working?
Hmm. The repo from the article works everytime. But I can't figure out why yours only worked once for me

**Comment by dtkdt100** [comment]
Interesting, not sure why it is not working every time.
Each time when you open the app you tap the "active service" button? 
Any special behavior that you notice when the notification doesn't appear?

**Comment by jtkeyva** [comment]
correct. no i don't notice anything. but your buttons are kinda awkward and the true false indicator is a bit confusing as well. i suggest making it a switch like as in the example to make it obvious that the feature is on. not sure what that true/false thing is showing.

i can do some more testing if you can clean up that ui a bit to be certain

**Comment by dtkdt100** [comment]
Ok, I will change it to a toggle, good idea. I will let you know when it is finished

Thank you very much 🙏

**Comment by dtkdt100** [comment]
@jtkeyva 
Hi! I did change it to switch widget. I notice something weird, on my iphone 11 it works every time (i tried 10 in a row) but on my iphone 6s it works barly once.

Witch iphone do u use?

**Comment by jtkeyva** [comment]
12 Pro

That other example from the tutorial works every time on it. And ya yours was working like once out of 10

**Comment by dtkdt100** [comment]
I will look at the article's example deeply and I will try to understand what is causing the issue and fix it.

**Comment by dtkdt100** [comment]
I think I fixed it. The problem was that the onKill function is not overrided the main onKill function in the AppDelegate.swift.

Checkout version 0.0.4

**Comment by jtkeyva** [comment]
cool, good job! yes now it works every time. but it seems to be a different notification? before it was silent with a white background. now it plays a sound and has the frosted background. is this intentional? if so, why?

now yeah a readme of how to implement this into an app would be helpful as i'm sure there are some special instructions.

thank you

**Comment by jtkeyva** [comment]
just saw this. i claime it can notify on app termination or kill. could be interesting to see what they did
https://pub.dev/packages/awesome_notifications

**Comment by dtkdt100** [comment]
Yes, the sound and vibration are intentional. You can edit these settings with

```dart
ArgsForIos argsForIos = ArgsForIos(
  interruptionLevel: InterruptionLevel.critical,
  useDefaultSound: true,
);
```

Regaurding awesome_notifications, I don't think it is excaly the same behavior as I wanted. "Store events to be fired when app is on Foreground"

![image](https://github.com/dtkdt100/notification_when_app_is_killed/assets/63166757/b4fe3081-9322-4aa5-b790-0a9f21082634)

**Comment by jtkeyva** [comment]
Got it.

This is in the readme FYI:
Notifications could be created at any moment (on Foreground, Background or even when the application is terminated/killed).

**Comment by dtkdt100** [comment]
Yes, but they probably don't have a listener to when the app is killed like we do (my package overrides the "onTeminate")
